general:
  production: True
  tarball: False

cdn:
  use_cdn: False
  cdn_root: /var/www/ddragon.bangingheads.net/
  cdn_url: https://ddragon.bangingheads.net/cdn

cloudflare:
  purge_cloudflare: False
  cloudflare_zone_id: YOUR_ZONE_ID
  cloudflare_email: example@bangingheads.net
  cloudflare_auth_key: YOUR_CLOUDFLARE_API_AUTH_KEY
